name: Release

on:
  workflow_dispatch:
    inputs:
      version:
        description: "Version to release (e.g. 2.7.0)"
        required: true
        type: string
      dry_run:
        description: "Dry run"
        required: true
        type: boolean

permissions:
  contents: write

jobs:
  build:
    name: Build for ${{ matrix.destination.name }}
    runs-on: ${{ matrix.destination.os }}
    strategy:
      matrix:
        destination:
          - { name: "ubuntu-aarch64", os: ubuntu-22.04-arm }
          - { name: "ubuntu-x86_64", os: ubuntu-22.04 }
          - { name: "macos-universal", os: macos-26 }
    steps:
    - if: startsWith(matrix.destination.name, 'ubuntu')
      uses: vapor/swiftly-action@v0.2
      with:
        toolchain: "6.2"
    - if: startsWith(matrix.destination.name, 'macos')
      run: sudo xcode-select -s /Applications/Xcode_26.3.app

    - uses: actions/checkout@v6
    - name: Update Sources/Mockolo/Version.swift
      run: echo "let version = \"${{ inputs.version }}\"" > Sources/Mockolo/Version.swift
    - name: Create the binary
      run: ./install-script.sh -s . -t mockolo -d . -o mockolo.${{ matrix.destination.name }}.tar.gz
    - name: Upload the binary
      uses: actions/upload-artifact@v6
      with:
        name: mockolo.${{ matrix.destination.name }}.tar.gz
        path: mockolo.${{ matrix.destination.name }}.tar.gz
        archive: false

  check-portability:
    needs: build
    name: TestRun on ${{ matrix.destination.os }} for ${{ matrix.destination.name }}
    runs-on: ${{ matrix.destination.os }}
    strategy:
      fail-fast: false
      matrix:
        destination:
          - { name: "ubuntu-x86_64", os: ubuntu-24.04 }
          - { name: "ubuntu-x86_64", os: ubuntu-22.04 }
          - { name: "ubuntu-aarch64", os: ubuntu-24.04-arm }
          - { name: "ubuntu-aarch64", os: ubuntu-22.04-arm }
          - { name: "macos-universal", os: macos-26 }
          - { name: "macos-universal", os: macos-15 }
          - { name: "macos-universal", os: macos-14 }
    steps:
    - uses: actions/download-artifact@v8
      with:
        name: mockolo.${{ matrix.destination.name }}.tar.gz
        skip-decompress: true
    - name: Unpack the binary
      run: tar -xvf mockolo.${{ matrix.destination.name }}.tar.gz
    - name: Run the binary
      run: ./mockolo --version

  make-artifact-bundle:
    needs: [build]
    runs-on: ubuntu-latest
    outputs:
      checksum: ${{ steps.checksum.outputs.checksum }}
    steps:
      - uses: actions/checkout@v6
      - name: Download all artifacts
        uses: actions/download-artifact@v8
        with:
          merge-multiple: true
          skip-decompress: true

      - run: bundle/make_artifactbundle.sh "${{ inputs.version }}"
      
      - name: Upload artifact bundle
        uses: actions/upload-artifact@v7
        with:
          name: mockolo.artifactbundle.zip
          path: mockolo.artifactbundle.zip
          # GitHub re-compresses the zip file, resulting in a broken zip file
          archive: false

      - name: Compute checksum
        id: checksum
        run: echo "checksum=$(swift package compute-checksum mockolo.artifactbundle.zip)" | tee -a "$GITHUB_OUTPUT"

  publish:
    if: ${{ !inputs.dry_run }}
    needs: [check-portability, make-artifact-bundle]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/download-artifact@v8
      with:
        merge-multiple: true
        skip-decompress: true

    - name: Publish to GitHub Releases
      uses: softprops/action-gh-release@v2
      with:
        name: ${{ inputs.version }}
        tag_name: ${{ inputs.version }}
        target_commitish: ${{ github.sha }}
        body: |
          ## For Build Tools Plugin (artifactbundle)

          ```swift
          .binaryTarget(
              name: "mockolo",
              url: "https://github.com/${{ github.repository }}/releases/download/${{ inputs.version }}/mockolo.artifactbundle.zip",
              checksum: "${{ needs.make-artifact-bundle.outputs.checksum }}"
          ),
          ```
        generate_release_notes: true
        files: |
          mockolo.ubuntu-x86_64.tar.gz
          mockolo.ubuntu-aarch64.tar.gz
          mockolo.macos-universal.tar.gz
          mockolo.artifactbundle.zip
        fail_on_unmatched_files: true
        draft: true
